### ISSUE TITLE
Support for aspect ratio

### ISSUE THREAD

**Issue by TeemuSuoranta** [16patsle/lazysizes#1]
I'd like to add aspect ratio support for lazysizes. By defining aspect ratio lazysizes takes up right amount of height before being loaded so it won't jank the text up and down when loading images.

This can be done with lazysizes native plugin https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/aspectratio and only requires defining `data-aspectratio` that can be set to `$width/$height` that can be pretty easily parsed with regex.

I have worked with WordPress image regex and lazysizes a bunc and could probably make this as an pull request if you want.

**Comment by 16patsle** [comment]
That sounds like a good feature to have, yes. If you want to implement it and do a PR, I would be very grateful.

**Comment by TeemuSuoranta** [comment]
I close this issue as the PR is in and further discussion can be done there.
